openapi: 3.0.0
info:
  version: 1.0.0
  title: CT Magazine Store
  description: An example API to demonstrate the capabilities of OAS 3.
  contact:
    name: CT Redaktion
    email: 'redaktion@heise.de'
    url: 'http://heise.de'
  license:
    name: MIT
servers:
  - url: 'https://github.com/manuelottlik/ct-oas/oas.yaml'
paths: 
  /magazines:
    get:
      description: |
        Returns all magazines
      operationId: findMagazines
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: magazine response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Magazine'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new magazine in the store.  Duplicates are allowed
      operationId: addMagazine
      requestBody:
        description: Magazine to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMagazine'
      responses:
        '201':
          description: magazine response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Magazine'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Magazine:
      allOf:
        - $ref: '#/components/schemas/NewMagazine'
        - required:
          - id
          properties:
            id:
              type: integer
              format: int64

    NewMagazine:
      required:
        - name  
      properties:
        name:
          type: string
        tag:
          type: string    

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
